name: Appflow Live Deploy Notification

on:
  push:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'package.json'
      - 'angular.json'
      - 'ionic.config.json'

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Appflow Deployment Notification
        run: |
          echo "🚀 Code pushed to GitHub!"
          echo "📱 Ionic Appflow is automatically building and deploying this update."
          echo ""
          echo "Since your Appflow is connected to GitHub:"
          echo "1. ✅ Appflow detected this push"
          echo "2. ⏳ Appflow is building the web assets"
          echo "3. 📲 Update will be available on devices soon"
          echo ""
          echo "Check your Appflow dashboard at:"
          echo "https://dashboard.ionicframework.com/app/1e8beef6/commits"
          echo ""
          echo "No additional action needed - Appflow handles everything!"

  # Only rebuild native app if native files changed
  rebuild-native:
    runs-on: macos-latest
    if: |
      contains(github.event.commits[0].modified, 'ios/') ||
      contains(github.event.commits[0].modified, 'capacitor.config') ||
      contains(github.event.commits[0].modified, 'package.json')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Trigger native build
        run: echo "Native files changed - rebuild required"
        
      # Your existing TestFlight build workflow here